"""delete unique constraint from reviews

Revision ID: 2a17cfa8e9e6
Revises: 369fc19fc2b7
Create Date: 2026-04-06 14:44:53.351474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a17cfa8e9e6'
down_revision: Union[str, None] = '369fc19fc2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_user_product', 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_review_user_product', 'reviews', ['user_id', 'product_id'])
    # ### end Alembic commands ###
