"""add rating to products

Revision ID: 369fc19fc2b7
Revises: 17de2bc35eb3
Create Date: 2026-04-06 14:32:14.385897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369fc19fc2b7'
down_revision: Union[str, None] = '17de2bc35eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
